name: back
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.4

# Add regular dependencies here.
dependencies:
  shelf: ^1.4.2
  shelf_router: ^1.1.4

  shelf_cors_headers: ^0.1.5
  dart_jsonwebtoken: ^3.1.1
  jwt_decoder: ^2.0.1
  dart_amqp: ^0.3.1
  shelf_web_socket: ^2.0.1
  web_socket_channel: ^3.0.2
  stomp_dart_client: ^2.1.3
  # shelf_logging: ^0.1.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
